language: c

before_install:
    sudo apt-get update

install:
    sudo apt-get install cmake cbmc

script:
    mkdir build && cd build && cmake .. && make && cest -V

#after_success:

#after_failure:

#after_script:

#before_deploy:
    #cd build && cpack

#deploy:

#after_deploy:
